const AssetContants = {
  client1: "/assets/svg/client1.svg",
  client2: "/assets/svg/client2.svg",
  client3: "/assets/svg/client3.svg",
  client4: "/assets/svg/client4.svg",
  client5: "/assets/svg/client5.svg",
  contact1: "/assets/svg/contact1.svg",
  contact2: "/assets/svg/contact2.svg",
  contact3: "/assets/svg/contact3.svg",
  provider1: "/assets/svg/provider1.svg",
  provider2: "/assets/svg/provider2.svg",
  provider3: "/assets/svg/provider3.svg",
  tech1: "/assets/svg/tech1.svg",
  tech2: "/assets/svg/tech2.svg",
  tech3: "/assets/svg/tech3.svg",
  tech4: "/assets/svg/tech4.svg",
  tech5: "/assets/svg/tech5.svg",
  tech6: "/assets/svg/tech6.svg",
  tech7: "/assets/svg/tech7.svg",
  tech8: "/assets/svg/tech8.svg",
  tools1: "/assets/svg/tools1.svg",
  tools2: "/assets/svg/tools2.svg",
  tools3: "/assets/svg/tools3.svg",
  tools4: "/assets/svg/tools4.svg",

  info: "/assets/png/info.png",
  logo: "/assets/png/logo.png",
  project1: "/assets/png/project1.png",
  project2: "/assets/png/project2.png",
  project3: "/assets/png/project3.png",
  project4: "/assets/png/project4.png",
  project5: "/assets/png/project5.png",
  project6: "/assets/png/project6.png",
  services1: "/assets/png/services1.png",
  services2: "/assets/png/services2.png",
  services3: "/assets/png/services3.png",
  services4: "/assets/png/services4.png",

  homeBg: "/assets/video/home-bg.mp4",
  otherBg: "/assets/video/other-bg.mp4",
};

export default AssetContants;
